{
 "title": "SPOOK",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "CPU & RAM Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Process CPU usage (1 core)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "grafana_cpu_usage", "legendFormat": "Grafana CPU Usage" },
    { "expr": "process_cpu_usage", "legendFormat": "Receiver CPU Usage" }
   ]
  },
  {
   "title": "Total CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "total_cpu_usage", "legendFormat": "Total CPU Usage" }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    { "expr": "grafana_memory_bytes / 1000000", "legendFormat": "Grafana RAM usage" },
    {
     "expr": "receiver_memory_bytes / 1000000",
     "legendFormat": "Receiver RAM usage"
    }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{chip=\"pci0000:00_0000:00:18_3\"}",
     "legendFormat": "CPU Temperature"
    }
   ]
  },
  { "title": "Packet Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Packets received (Node)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_packets_total{device=\"lo\"}[10s])",
     "legendFormat": "loopback"
    },
    {
     "expr": "rate(node_network_receive_packets_total{device=\"eno1\"}[10s])",
     "legendFormat": "ethernet"
    }
   ]
  },
  {
   "title": "Packets sent (Node)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_packets_total{device=\"lo\"}[10s])",
     "legendFormat": "loopback"
    },
    {
     "expr": "rate(node_network_transmit_packets_total{device=\"eno1\"}[10s])",
     "legendFormat": "ethernet"
    }
   ]
  },
  {
   "title": "RX Packets dropped (Node)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "expr": "rate(node_network_receive_drop_total{device=\"lo\"}[10s])",
     "legendFormat": "loopback"
    },
    {
     "expr": "rate(node_network_receive_drop_total{device=\"eno1\"}[10s])",
     "legendFormat": "ethernet"
    }
   ]
  },
  {
   "title": "RX Megabytes (Node)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=\"lo\"}[10s]) / 1000000",
     "legendFormat": "loopback"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{device=\"eno1\"}[10s]) / 1000000",
     "legendFormat": "ethernet"
    }
   ]
  },
  {
   "title": "RX Megabytes (App)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "rate(bytes_received_total[10s]) / 1000000",
     "legendFormat": "App bytes RX"
    }
   ]
  },
  {
   "title": "PCIE RX Overflow ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 20 },
   "targets": [
    { "expr": "pcie_rx_overflow", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Packets received Per Second (app)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(packets_received_total[15s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.55, rate(latency_ms_bucket[10s]))",
     "legendFormat": "55%"
    },
    {
     "expr": "histogram_quantile(0.95, rate(latency_ms_bucket[10s]))\n",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.99, rate(latency_ms_bucket[10s]))",
     "legendFormat": "99%"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "packets_lost_total", "legendFormat": "__auto" }
   ]
  },
  { "title": "GPU Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "GPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "DCGM_FI_DEV_GPU_TEMP", "legendFormat": "GPU {{gpu}}" }
   ]
  },
  {
   "title": "GPU Memory Temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "DCGM_FI_DEV_MEMORY_TEMP", "legendFormat": "GPU {{gpu}}" }
   ]
  },
  {
   "title": "GPU Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "DCGM_FI_DEV_POWER_USAGE", "legendFormat": "GPU {{gpu}}" }
   ]
  },
  {
   "title": "GPU Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "DCGM_FI_DEV_GPU_UTIL", "legendFormat": "GPU {{gpu}}" }
   ]
  },
  {
   "title": "GPU Memory Used (MB)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    { "expr": "DCGM_FI_DEV_FB_USED / 1000000", "legendFormat": "Used GPU {{gpu}}" }
   ]
  },
  {
   "title": "GPU PCIe RX / TX (Bytes/sec)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(DCGM_FI_DEV_PCIE_RX_BYTES[10s])",
     "legendFormat": "RX GPU {{gpu}}"
    },
    {
     "expr": "rate(DCGM_FI_DEV_PCIE_TX_BYTES[10s])",
     "legendFormat": "TX GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "Holoscan End-to-End Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "holoscan_latency_ms", "legendFormat": "Latency" }
   ]
  },
  {
   "title": "Holoscan Message Rate (msg/s)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    { "expr": "holoscan_message_rate", "legendFormat": "Message Rate" }
   ]
  },
  {
   "title": "GPU Memory Bandwidth Utilisation (%)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "DCGM_FI_DEV_MEM_COPY_UTIL", "legendFormat": "Mem BW GPU {{gpu}}" }
   ]
  },
  {
   "title": "GPU NVLink Throughput (Bytes/sec)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(DCGM_FI_DEV_NVLINK_BANDWIDTH_TOTAL[10s])",
     "legendFormat": "NVLink GPU {{gpu}}"
    }
   ]
  }
 ]
}