global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'udp_receiver'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.1.44:8000']  # For Docker Desktop (Mac/Windows)
      # For Linux, use your actual host IP like: ['192.168.1.100:8000']
  
  - job_name: 'node'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.1.44:9100']  # For Docker Desktop (Mac/Windows)
      # For Linux, use your actual host IP like: ['192.168.1.100:9100']